### ISSUE TITLE
mod receives identify event but doesn't respond to it

### ISSUE THREAD

**Issue by Mass1milian0** [jubiman/DeviousDiscord#13]
i have been debugging the server, and i've noticed that the discord to mc bridge wasn't working
and that the console was filling up with undefined channel id

after some local testing i found that as soon as the client connects to the websocket, it asks the new connection to identify itself (through the identify event) but it never receieves a response, the server still partially works because often time the server is passed as a data from the event but this breaks a lot of functionality

![image](https://github.com/jubiman/DeviousDiscord/assets/20503622/3a0d12dc-f30b-4653-a154-e6fb5eb30d41)
![image](https://github.com/jubiman/DeviousDiscord/assets/20503622/89201b40-8359-44db-b562-aa783c05edb4)

if you see the logs it receives the identify event but never responds, when i manually reconnect using the command, everything works as expected

**Comment by jubiman** [comment]
Seems like this is due to the ServerState event being sent while identify is being sent, which raises an IllegalStateException: Send pending in the websocket implementations from 1.18+ (might also happen in 1.12.2, but I don't think so). I guess I'll have to create a custom queuing system -_-

Will be fixed in v1.2.0 asap

**Comment by Mass1milian0** [comment]
i mitigated the issue by implementing a backup identification system, until this is fixed, my server listens for any form of identification (usually sent as a server param) and updates the connection list accordingly, if you prefer, you can omit sending me identification on startup, since my server will ask for identification as soon as the websocket connects, all it would have to do is answer the request

**Comment by jubiman** [comment]
Fixed in v1.2.0
